name: Deploy Website to Azure VM

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh

          printf '%s\n' "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'

          if [ ! -d ~/nova-3d-cicd ]; then
              git clone https://github.com/roshanhaneen05/nova-3d-cicd.git ~/nova-3d-cicd
          fi

          cd ~/nova-3d-cicd

          git pull origin main

          sudo mkdir -p /var/www/threed-demo

          sudo rm -rf /var/www/threed-demo/*

          sudo cp -r index.html css js vendor /var/www/threed-demo/

          sudo chown -R www-data:www-data /var/www/threed-demo

          sudo nginx -t

          sudo systemctl restart nginx

          echo "Deployment Successful"

          EOF

      - name: Verify Deployment
        run: |
          curl --fail http://${{ secrets.HOST }}